### ISSUE TITLE
debug not defined

### ISSUE THREAD

**Issue by Damaris84** [carst/slideBox.js#1]
Hello,
I installed the plugin and did everything according to the instructions.
Yet, it shows an error in the console:

```
jquery-3.1.1.min.js:2 Uncaught ReferenceError: debug is not defined
    at initSlides (slidebox-min.js:1)
    at HTMLDocument.<anonymous> (index.php:629)
    at j (jquery-3.1.1.min.js:2)
    at k (jquery-3.1.1.min.js:2)
```
and when I click on the image, it does not open.
What do I need to do?

Thank you!
Damaris

**Comment by carst** [comment]
Hello Damaris, 

Please download the latest version of the plugin, and you should be fine. Sorry for not replying earlier! The error happened because I was not smart enough to set some global variables in the right file.

The variables by the way are debug, mobile and imgDirDefault. I want to add some JS configuration options to the plugin in the future, and will add some documentation then too.
